spring:
  application:
    name: tensquare-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.200.132:3306/tensquare_base?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    database: MySQL
sms:
  ip: 129.168.2.12344343
